PermitRootLogin no
PasswordAuthentication yes
PermitEmptyPasswords no
AllowUsers student
AllowTcpForwarding yes
GatewayPorts no
X11Forwarding no
PrintMotd yes
ClientAliveInterval 60
ClientAliveCountMax 10
